Rebase with Upstream and Port to Python3
cristian99garcia/PolariActivity pull request #7
Opened 2020-06-10 15:27 UTC by Saumya-Mishra9129

Twisted uses a module named 'attr' which I couldn't find in sugar . So I installed it manually using pip (apt-get didn't work) with following command-

`sudo pip install attrs `

Also we need to install OpenSSL with `sudo apt-get install python3-openssl` to get it working.

@chimosky @quozl @srevinsaju Please Review.

2020-06-10 15:28 UTC, srevinsaju commented
Nice; will review it now.
OMG: heavy diff

2020-06-10 15:44 UTC, srevinsaju requested changes
Reviewing is tedious, 555 files from the last two commits. Some minor corrections; Will update you with sugar testing

2020-06-10 15:44 UTC, srevinsaju commented on afk_manager.py
> +            if nickname in list(self.timeout_ids.keys()):
`list` function can be ignored. I assume these were created by `2to3`. 
As mentioned [here](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md),
> Port from Python 2 to Python 3. Start your porting with 2to3 tool,
> In the terminal, type:
> `2to3 -w -n *.py`
> and then **_review_ every change made,**

2020-06-10 15:44 UTC, srevinsaju commented on afk_manager.py
> +        if nickname in list(self.timeout_ids.keys()):
same

2020-06-10 15:44 UTC, srevinsaju commented on chat_box.py
> +        for channel in list(self.nicks.keys()):
same

2020-06-10 15:44 UTC, srevinsaju commented on chat_box.py
> +        for channel in list(self.nicks.keys()):
here also

2020-06-10 15:44 UTC, srevinsaju commented on constantly/_constants.py
> +        for (name, descriptor) in list(attributes.items()):
This can be made more readable by
```python
>>> a = {'a':"apple", 'b':"ball", 'c':"cat"}
>>> for name, descriptor in a.items():
...     print(name, descriptor)
... 
a apple
b ball
c cat
>>> 

```

Notice the extra parenthesis has been removed; and list function also has been removed

2020-06-10 15:46 UTC, Saumya-Mishra9129 commented
> Twisted uses a module named 'attr' which I couldn't find in sugar . So I installed it manually using pip (apt-get didn't work) with following command-
`sudo pip install attrs`

I now found out that we don't need to do this. It will get install when we run -
`sudo apt-get install python3-service-identity` It is in Readme.md

2020-06-10 15:47 UTC, srevinsaju commented
Can we depend on distribution specific `twisted` and other packages? Need to consult others too.

this will probably reduce the work to be done. for example as has been done with Box2D in `physics` activity

2020-06-10 15:50 UTC, srevinsaju commented
@Saumya-Mishra9129 are you `defaultnick` who is joining #sugar?

2020-06-10 15:55 UTC, Saumya-Mishra9129 commented
> Can we depend on distribution specific `twisted` and other packages? Need to consult others too.
> 
> this will probably reduce the work to be done. for example as has been done with Box2D in `physics` activity

Yeah it is probably a good thing to be done. If others agree I will do that as well.

> @Saumya-Mishra9129 are you defaultnick who is joining #sugar?

Yes I tried to join with Polari.
Got an error

![Screenshot from 2020-06-10 20-05-52](https://user-images.githubusercontent.com/45252461/84290050-d3fced80-ab60-11ea-87f0-cd6878caa848.png)

2020-06-10 15:56 UTC, srevinsaju commented
It is currently very buggy, the UI is better than IRC activity though; I can get to the UI, but can do nothing; Getting lots of repeated errors 
```
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 127: invalid contin
uation byte
```
Its possible that some files used within is buggy or is a escape character; probably it was not encoded in the proper charset

2020-06-10 15:56 UTC, Saumya-Mishra9129 commented on afk_manager.py
> +            if nickname in list(self.timeout_ids.keys()):
Yeah it is created by 2to3. I will fix that

2020-06-10 15:59 UTC, Saumya-Mishra9129 commented
> It is currently very buggy, the UI is better than IRC activity though; I can get to the UI, but can do nothing; Getting lots of repeated errors
> 
> ```
> builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 127: invalid contin
> uation byte
> ```
> 
> Its possible that some files used within is buggy or is a escape character; probably it was not encoded in the proper charset

The error is in while irc.py inside twisted, seems like after port to python3 because all strings are stored as Unicode in an instance of the str type, there can be bugs in twisted.

2020-06-10 16:01 UTC, srevinsaju commented
Ok, I am not spamming #sugar any more; 
> seems like after port to python3 because unicode strings are not accepted, there is bugs in twisted.

Twisted is a good repository, and maintained. If there was an error, it should have been found out before. It seems like correct data types were not passed as parameters. It will require advance debugging however


_________


Btw, there is a typo in PR title

2020-06-10 16:07 UTC, Saumya-Mishra9129 commented
> Twisted is a good repository, and maintained. If there was an error, it should have been found out before. It seems like correct data types were not passed as parameters. It will require advance debugging however

Yeah possible, I agree with you , It would need debugging of source code.

2020-06-10 23:18 UTC, chimosky commented
@Saumya-Mishra9129 said
> Yeah it is probably a good thing to be done. If others agree I will do that as well.

Yeah I agree, use distro specific packages where possible. 

In `setup.py` `cmd_genpot` add `--from-code=UTF-8` as part of your args to `xgettext` as an error is thrown by `xgettext` when trying to parse some strings. See https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/ecf335c19cb80471dcda8d2481382bf5d34c6a5f.

Didn't review cd8a53e...5814bac as I can't properly view the diff of the aggregate change.
I'll wait for you to use distro specific packages before reviewing.

2020-06-11 19:37 UTC, Saumya-Mishra9129 commented
> Didn't review cd8a53e...5814bac as I can't properly view the diff of the aggregate change.
I'll wait for you to use distro specific packages before reviewing.

It is done. Please review.

2020-06-29 05:01 UTC, quozl commented
What do you need for the UnicodeDecodeError?  Are all the source files UTF-8 encoded, and do they contain only UTF-8?

2020-07-08 15:13 UTC, Saumya-Mishra9129 commented
Update - UnicodeDecodeError is fixed in d4b7c80. I have tested also works fine. @chimosky @srevinsaju @quozl Please Review.

2020-07-09 05:02 UTC, quozl commented
Thanks.

Fixes https://github.com/sugarlabs/PolariActivity/issues/6

Polari upstream has changed from Python to JavaScript.  But this code remains Python.  When you say you rebased with upstream, what did you do?

Reviewed.  Prepared a diffstat.  Most of the change is to remove the embedded twisted, which is good.

Tested.  Speaking on #sugar without registration gives no message.  A message is sent to the client by the server but is not displayed.

2020-07-09 05:15 UTC, Saumya-Mishra9129 commented
> Polari upstream has changed from Python to JavaScript. But this code remains Python. When you say you rebased with upstream, what did you do?

By rebasing with upstream I thought of rebasing libraries used ( twisted , zope, incremental and constantly) with their upstream sources. So I first did that, but then @chimosky suggested to use distro specific twisted ,which I have done later.

2020-07-09 05:36 UTC, quozl commented
I see, thanks.  Our toolkit doesn't have support for JavaScript GObject Introspection apps, so rebasing Polari itself would be a major undertaking requiring new toolkit code as well.  I don't think we need that yet.  But you might check for changes to Polari between the time this source code was copied and before _they_ switched to JavaScript.

2020-08-10 07:47 UTC, Saumya-Mishra9129 commented
> I see, thanks. Our toolkit doesn't have support for JavaScript GObject Introspection apps, so rebasing Polari itself would be a major undertaking requiring new toolkit code as well. I don't think we need that yet. But you might check for changes to Polari between the time this source code was copied and before _they_ switched to JavaScript.
> 

Thanks, for Polari source code, I couldn't find source code which was related to Python3 and also that's so old also.

>That could be a separate pull request though.

Thanks I will make a different one. Until then you can merge these changes.

2020-08-11 05:45 UTC, quozl commented
I've checked again, and I no longer think this activity has any association with the GNOME Polari app.  Polari activity is an independent implementation using Twisted, and the name is coincidental.

2020-08-11 05:45 UTC, merged